# -*- coding: utf-8 -*-
"""Primeiro exercício - Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FqEozm57482cmU9ypfj4fPXnn0U6fMu2
"""

# Identificação do usuário/ boas vindas
usuario= input('Digite aqui seu nome: ')
print('Seja bem-vindo(a)', usuario)

# Para receber os números
print('\nVamos calcular')
while True:
 num1= int(input('Digite o primeiro número: '))
 break
while True:
 num2= int(input('Digite o segundo número: '))
 break

# Para escolher os cálculos
print("\nQual operação deseja realizar?")
print("1 - Adição")
print("2 - Subtração")
print("3 - Multiplicação")
print("4 - Divisão")
operacao = input("\nDigite o número da operação: ")

# Operações possíveis
if operacao == "1":
    resultado = num1 + num2
    print("Resultado:", resultado)

elif operacao == "2":
    resultado = num1 - num2
    print("Resultado:", resultado)
    if resultado < 0:
        print("O resultado é um número negativo:", resultado)
    else:
        print("Resultado:", resultado)

elif operacao == "3":
    resultado = num1 * num2
    print("Resultado:", resultado)

elif operacao == "4":
    if num2 != 0:
        resultado = num1 / num2
        print("Resultado:", resultado)
    else:
        print("Não é possível dividir por zero.")
else:
    print("Operação inválida! Escolha uma opção de 1 a 4")

# Para refazer outras opções de cálculo
while True:
 continuar = input("\nDeseja realizar outra operação? (s/n): ")

 if continuar.lower() != "s":
    print("Calculadora encerrada.")
 break